// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: signal.proto

package ophelia_ci

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Signals_CommitSignal_FullMethodName = "/signal.Signals/CommitSignal"
)

// SignalsClient is the client API for Signals service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignalsClient interface {
	CommitSignal(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*Empty, error)
}

type signalsClient struct {
	cc grpc.ClientConnInterface
}

func NewSignalsClient(cc grpc.ClientConnInterface) SignalsClient {
	return &signalsClient{cc}
}

func (c *signalsClient) CommitSignal(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Signals_CommitSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignalsServer is the server API for Signals service.
// All implementations must embed UnimplementedSignalsServer
// for forward compatibility.
type SignalsServer interface {
	CommitSignal(context.Context, *CommitRequest) (*Empty, error)
	mustEmbedUnimplementedSignalsServer()
}

// UnimplementedSignalsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignalsServer struct{}

func (UnimplementedSignalsServer) CommitSignal(context.Context, *CommitRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitSignal not implemented")
}
func (UnimplementedSignalsServer) mustEmbedUnimplementedSignalsServer() {}
func (UnimplementedSignalsServer) testEmbeddedByValue()                 {}

// UnsafeSignalsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignalsServer will
// result in compilation errors.
type UnsafeSignalsServer interface {
	mustEmbedUnimplementedSignalsServer()
}

func RegisterSignalsServer(s grpc.ServiceRegistrar, srv SignalsServer) {
	// If the following call pancis, it indicates UnimplementedSignalsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Signals_ServiceDesc, srv)
}

func _Signals_CommitSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalsServer).CommitSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signals_CommitSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalsServer).CommitSignal(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Signals_ServiceDesc is the grpc.ServiceDesc for Signals service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Signals_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "signal.Signals",
	HandlerType: (*SignalsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitSignal",
			Handler:    _Signals_CommitSignal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signal.proto",
}
