name: ophelia-ci-server
base: core24
version: 1.0.0
summary: An open and free CI server.
description: |
  A CI server that anyone can install in a VM and use to mange 
  their projects with CI workflows.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  ophelia-ci-server:
    command: bin/ophelia-ci-server
    daemon: simple
    plugs:
      - network
      - network-bind
      # - lxd
      - home
      - ssh-keys
      - account-control

parts:
  my-part:
    plugin: go
    build-snaps: [go/latest/stable]
    source-type: git
    source: https://github.com/EdmilsonRodrigues/ophelia-ci-server
