name: ophelia-ci-server
summary: An open and free CI server.
description: |
  A CI server that anyone can install in a VM and use to mange 
  their projects with CI workflows.
adopt-info: woke

grade: devel
confinement: devmode
base: core22

apps:
  ophelia-ci-server:
    command: bin/ophelia-ci-server
    daemon: simple
    plugs: 
      - network
    user: git
    group: git

parts:
  ophelia-ci-server:
    plugin: go
    source: https://github.com/EdmilsonRodrigues/ophelia-ci-server
    source-type: git
    override-build: |
      snapcraftctl build
      addgroup --system git
      adduser --system --ingroup git --home /var/lib/git git
