apiVersion: v1
kind: Pod
metadata:
  name: ophelia-ci-server
  labels:
    app: ophelia-ci-server
spec:
  containers:
    - name: ophelia-ci-server
      image: edmilsonrodrigues/ophelia-ci-server:1.0.0
      ports:
      - containerPort: 50051

