apiVersion: v1
kind: Pod
metadata:
  name: ophelia-ci-interface
  labels: 
    app: ophelia-ci-interface
spec:
  containers:
  - name: ophelia-ci-interface
    image: edmilsonrodrigues/ophelia-ci-interface:1.0.0
    ports:
    - containerPort: 8000
    env:
    - name: APP_OPHELIA_CI_UNPACKED
      value: "True"
    - name: APP_OPHELIA_CI_GRPC_SERVER
      value: "10.152.183.81:50051"
