# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x12\x07ophelia\"\x07\n\x05\x45mpty29\n\rHealthService\x12(\n\x06Health\x12\x0e.ophelia.Empty\x1a\x0e.ophelia.EmptyB)Z\'github.com/EdmilsonRodrigues/ophelia-cib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/EdmilsonRodrigues/ophelia-ci'
  _globals['_EMPTY']._serialized_start=25
  _globals['_EMPTY']._serialized_end=32
  _globals['_HEALTHSERVICE']._serialized_start=34
  _globals['_HEALTHSERVICE']._serialized_end=91
# @@protoc_insertion_point(module_scope)
