"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CommitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COMMIT_HASH_FIELD_NUMBER: builtins.int
    BRANCH_FIELD_NUMBER: builtins.int
    REPOSITORY_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    commit_hash: builtins.str
    branch: builtins.str
    repository: builtins.str
    tag: builtins.str
    def __init__(
        self,
        *,
        commit_hash: builtins.str = ...,
        branch: builtins.str = ...,
        repository: builtins.str = ...,
        tag: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["branch", b"branch", "commit_hash", b"commit_hash", "repository", b"repository", "tag", b"tag"]) -> None: ...

global___CommitRequest = CommitRequest
