# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x07ophelia\"2\n\x1e\x41uthenticationChallengeRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"4\n\x1f\x41uthenticationChallengeResponse\x12\x11\n\tchallenge\x18\x01 \x01(\t\"<\n\x15\x41uthenticationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tchallenge\x18\x02 \x01(\t\">\n\x16\x41uthenticationResponse\x12\x15\n\rauthenticated\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\".\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"9\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\nprivateKey\x18\x02 \x01(\t\"E\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x12\n\nprivateKey\x18\x03 \x01(\t\",\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"8\n\x10ListUserResponse\x12$\n\x05users\x18\x01 \x03(\x0b\x32\x15.ophelia.UserResponse\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xce\x01\n\x0b\x41uthService\x12l\n\x17\x41uthenticationChallenge\x12\'.ophelia.AuthenticationChallengeRequest\x1a(.ophelia.AuthenticationChallengeResponse\x12Q\n\x0e\x41uthentication\x12\x1e.ophelia.AuthenticationRequest\x1a\x1f.ophelia.AuthenticationResponse2\xbb\x02\n\x0bUserService\x12?\n\nCreateUser\x12\x1a.ophelia.CreateUserRequest\x1a\x15.ophelia.UserResponse\x12?\n\nUpdateUser\x12\x1a.ophelia.UpdateUserRequest\x1a\x15.ophelia.UserResponse\x12\x35\n\x08ListUser\x12\x0e.ophelia.Empty\x1a\x19.ophelia.ListUserResponse\x12\x39\n\x07GetUser\x12\x17.ophelia.GetUserRequest\x1a\x15.ophelia.UserResponse\x12\x38\n\nDeleteUser\x12\x1a.ophelia.DeleteUserRequest\x1a\x0e.ophelia.EmptyB)Z\'github.com/EdmilsonRodrigues/ophelia-cib\x06proto3')  # noqa: E501

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)  # noqa: E501
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)  # noqa: E501
if not _descriptor._USE_C_DESCRIPTORS:  # noqa: E501
  _globals['DESCRIPTOR']._loaded_options = None  # noqa: E501
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/EdmilsonRodrigues/ophelia-ci'  # noqa: E501
  _globals['_AUTHENTICATIONCHALLENGEREQUEST']._serialized_start=23
  _globals['_AUTHENTICATIONCHALLENGEREQUEST']._serialized_end=73
  _globals['_AUTHENTICATIONCHALLENGERESPONSE']._serialized_start=75
  _globals['_AUTHENTICATIONCHALLENGERESPONSE']._serialized_end=127
  _globals['_AUTHENTICATIONREQUEST']._serialized_start=129
  _globals['_AUTHENTICATIONREQUEST']._serialized_end=189
  _globals['_AUTHENTICATIONRESPONSE']._serialized_start=191
  _globals['_AUTHENTICATIONRESPONSE']._serialized_end=253
  _globals['_EMPTY']._serialized_start=255
  _globals['_EMPTY']._serialized_end=262
  _globals['_GETUSERREQUEST']._serialized_start=264
  _globals['_GETUSERREQUEST']._serialized_end=310
  _globals['_CREATEUSERREQUEST']._serialized_start=312
  _globals['_CREATEUSERREQUEST']._serialized_end=369
  _globals['_UPDATEUSERREQUEST']._serialized_start=371
  _globals['_UPDATEUSERREQUEST']._serialized_end=440
  _globals['_USERRESPONSE']._serialized_start=442
  _globals['_USERRESPONSE']._serialized_end=486
  _globals['_LISTUSERRESPONSE']._serialized_start=488
  _globals['_LISTUSERRESPONSE']._serialized_end=544
  _globals['_DELETEUSERREQUEST']._serialized_start=546
  _globals['_DELETEUSERREQUEST']._serialized_end=577
  _globals['_AUTHSERVICE']._serialized_start=580
  _globals['_AUTHSERVICE']._serialized_end=786
  _globals['_USERSERVICE']._serialized_start=789
  _globals['_USERSERVICE']._serialized_end=1104
# @@protoc_insertion_point(module_scope)
