"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AuthenticationChallengeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    username: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["username", b"username"]) -> None: ...

global___AuthenticationChallengeRequest = AuthenticationChallengeRequest

@typing.final
class AuthenticationChallengeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHALLENGE_FIELD_NUMBER: builtins.int
    challenge: builtins.str
    def __init__(
        self,
        *,
        challenge: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["challenge", b"challenge"]) -> None: ...

global___AuthenticationChallengeResponse = AuthenticationChallengeResponse

@typing.final
class AuthenticationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    CHALLENGE_FIELD_NUMBER: builtins.int
    username: builtins.str
    challenge: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        challenge: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["challenge", b"challenge", "username", b"username"]) -> None: ...

global___AuthenticationRequest = AuthenticationRequest

@typing.final
class AuthenticationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHENTICATED_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    authenticated: builtins.bool
    token: builtins.str
    def __init__(
        self,
        *,
        authenticated: builtins.bool = ...,
        token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["authenticated", b"authenticated", "token", b"token"]) -> None: ...

global___AuthenticationResponse = AuthenticationResponse

@typing.final
class GetUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    id: builtins.str
    username: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        username: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "username", b"username"]) -> None: ...

global___GetUserRequest = GetUserRequest

@typing.final
class CreateUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PUBLICKEY_FIELD_NUMBER: builtins.int
    username: builtins.str
    publicKey: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        publicKey: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["publicKey", b"publicKey", "username", b"username"]) -> None: ...

global___CreateUserRequest = CreateUserRequest

@typing.final
class UpdateUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    PUBLICKEY_FIELD_NUMBER: builtins.int
    id: builtins.str
    username: builtins.str
    publicKey: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        username: builtins.str = ...,
        publicKey: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "publicKey", b"publicKey", "username", b"username"]) -> None: ...

global___UpdateUserRequest = UpdateUserRequest

@typing.final
class UserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    id: builtins.str
    username: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        username: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "username", b"username"]) -> None: ...

global___UserResponse = UserResponse

@typing.final
class ListUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERS_FIELD_NUMBER: builtins.int
    @property
    def users(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UserResponse]: ...
    def __init__(
        self,
        *,
        users: collections.abc.Iterable[global___UserResponse] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["users", b"users"]) -> None: ...

global___ListUserResponse = ListUserResponse

@typing.final
class DeleteUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___DeleteUserRequest = DeleteUserRequest
