#!/bin/sh
set -e

LOG_FILE="/var/log/ophelia-ci-client-install.log"

log() {
    echo "$(date) - $1" >> $LOG_FILE
}

log "Starting installation"

log "Checking if client config exists"
if [ ! -f /etc/ophelia-ci/client-config.toml ]; then
    log "Client config does not exist, creating one"
    mkdir -p /etc/ophelia-ci
    cat <<EOF > /etc/ophelia-ci/client-config.toml
[client]
server = "localhost:50051"

[ssl]
# key_file = "/etc/ssl/private/ophelia-ci-client.key"  # If ssl required, put the path here
EOF
fi

log "Changing ownership of client config"
chown root:root /etc/ophelia-ci/client-config.toml
chmod 644 /etc/ophelia-ci/client-config.toml

exit 0