#!/bin/sh
set -e

LOG_FILE="/var/log/ophelia-ci-server-install.log"
OPHELIA_USER="ophelia"

log() {
    echo "$(date) - $1" >> $LOG_FILE
}

log "Starting installation"

log "Checking if server config exists"
if [ ! -f /etc/ophelia-ci/server-config.toml ]; then
    log "Server config does not exist, creating one"
    mkdir -p /etc/ophelia-ci
    cat <<EOF > /etc/ophelia-ci/server-config.toml
[server]
port = 50051
home_path = "/var/lib/ophelia/"
secret = "$(head -c 32 /dev/urandom | base64)"
expiration_time = 30  # in days

[ssl]
# cert_file = "/etc/ssl/certs/ophelia-ci-server.crt"  # If ssl required, put the path here
# key_file = "/etc/ssl/private/ophelia-ci-server.key"  # If ssl required, put the path here
EOF
fi

if ! id -g $OPHELIA_USER > /dev/null 2> /dev/null; then
    log "Creating $OPHELIA_USER group"
    addgroup --system $OPHELIA_USER
fi

if ! id -u $OPHELIA_USER > /dev/null 2> /dev/null; then
    log "Creating $OPHELIA_USER user"
    adduser --system --ingroup $OPHELIA_USER --home /var/lib/ophelia --shell /bin/bash $OPHELIA_USER
fi

if [ ! -d /var/lib/ophelia ]; then
    log "Creating $OPHELIA_USER directory"
    mkdir -p /var/lib/ophelia
fi

log "Changing ownership of $OPHELIA_USER directory"
chown ${OPHELIA_USER}:${OPHELIA_USER} /var/lib/ophelia
chmod 740 /var/lib/ophelia

log "Configuring Git for $OPHELIA_USER"
su - "$OPHELIA_USER" -c "git config --global user.email 'ophelia@your-domain.com'"
su - "$OPHELIA_USER" -c "git config --global user.name 'Ophelia CI Server'"

log "Changing ownership of server config"
chown root:ophelia /etc/ophelia-ci/server-config.toml
chmod 644 /etc/ophelia-ci/server-config.toml

log "Enabling and starting ophelia-ci-server service"
systemctl enable ophelia-ci-server.service
systemctl start ophelia-ci-server.service

exit 0