#!/bin/sh
set -e

LOG_FILE="/var/log/ophelia-ci-server-install.log"

log() {
    echo "$(date) - $1" >> $LOG_FILE
}

log "Starting installation"

log "Checking if server config exists"
if [ ! -f /etc/ophelia-ci/server-config.toml ]; then
    log "Server config does not exist, creating one"
    mkdir -p /etc/ophelia-ci
    cat <<EOF > /etc/ophelia-ci/server-config.toml
[server]
port = 50051
db_path = "/var/lib/ophelia/ophelia.db"
secret = "$(head -c 32 /dev/urandom | base64)"
expiration_time = 30  # in days

[ssl]
# cert_file = "/etc/ssl/certs/ophelia-ci-server.crt"  # If ssl required, put the path here
# key_file = "/etc/ssl/private/ophelia-ci-server.key"  # If ssl required, put the path here
EOF
fi

if ! id -g ophelia > /dev/null 2> /dev/null; then
    log "Creating ophelia group"
    addgroup --system ophelia
fi

if ! id -u ophelia > /dev/null 2> /dev/null; then
    log "Creating ophelia user"
    adduser --system --ingroup ophelia --home /var/lib/ophelia ophelia
fi

if [ ! -d /var/lib/ophelia ]; then
    log "Creating ophelia directory"
    mkdir -p /var/lib/ophelia
fi

log "Changing ownership of ophelia directory"
chown ophelia:ophelia /var/lib/ophelia
chmod 740 /var/lib/ophelia

log "Changing ownership of server config"
chown root:ophelia /etc/ophelia-ci/server-config.toml
chmod 644 /etc/ophelia-ci/server-config.toml

log "Enabling and starting ophelia-ci-server service"
systemctl enable ophelia-ci-server.service
systemctl start ophelia-ci-server.service

exit 0