#!/bin/sh
set -e

systemctl stop ophelia-ci-server.service || {
    echo "Failed to stop ophelia-ci-server.service" >&2
}
systemctl disable ophelia-ci-server.service || {
    echo "Failed to disable ophelia-ci-server.service" >&2
}

if [ "$1" = "remove" ] && [ "$2" = "purge" ]; then
    if id -u ophelia > /dev/null 2> /dev/null; then
        rm -rf /var/lib/ophelia
        rm -rf /etc/ophelia-ci/server-config.toml
        userdel -r ophelia
    fi
fi

systemctl daemon-reload --force
echo "Daemon reloaded"

exit 0