# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: repository.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'repository.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10repository.proto\x12\x0eophelia_server\"0\n\x14GetRepositoryRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"O\n\x17\x43reateRepositoryRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\tgitignore\x18\x03 \x01(\t\"H\n\x17UpdateRepositoryRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"%\n\x17\x44\x65leteRepositoryRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"C\n\x12RepositoryResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"R\n\x16ListRepositoryResponse\x12\x38\n\x0crepositories\x18\x01 \x03(\x0b\x32\".ophelia_server.RepositoryResponse2\xd5\x03\n\x11RepositoryService\x12_\n\x10\x43reateRepository\x12\'.ophelia_server.CreateRepositoryRequest\x1a\".ophelia_server.RepositoryResponse\x12_\n\x10UpdateRepository\x12\'.ophelia_server.UpdateRepositoryRequest\x1a\".ophelia_server.RepositoryResponse\x12O\n\x0eListRepository\x12\x15.ophelia_server.Empty\x1a&.ophelia_server.ListRepositoryResponse\x12Y\n\rGetRepository\x12$.ophelia_server.GetRepositoryRequest\x1a\".ophelia_server.RepositoryResponse\x12R\n\x10\x44\x65leteRepository\x12\'.ophelia_server.DeleteRepositoryRequest\x1a\x15.ophelia_server.EmptyB0Z.github.com/EdmilsonRodrigues/ophelia-ci-serverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'repository_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/EdmilsonRodrigues/ophelia-ci-server'
  _globals['_GETREPOSITORYREQUEST']._serialized_start=36
  _globals['_GETREPOSITORYREQUEST']._serialized_end=84
  _globals['_CREATEREPOSITORYREQUEST']._serialized_start=86
  _globals['_CREATEREPOSITORYREQUEST']._serialized_end=165
  _globals['_UPDATEREPOSITORYREQUEST']._serialized_start=167
  _globals['_UPDATEREPOSITORYREQUEST']._serialized_end=239
  _globals['_DELETEREPOSITORYREQUEST']._serialized_start=241
  _globals['_DELETEREPOSITORYREQUEST']._serialized_end=278
  _globals['_EMPTY']._serialized_start=280
  _globals['_EMPTY']._serialized_end=287
  _globals['_REPOSITORYRESPONSE']._serialized_start=289
  _globals['_REPOSITORYRESPONSE']._serialized_end=356
  _globals['_LISTREPOSITORYRESPONSE']._serialized_start=358
  _globals['_LISTREPOSITORYRESPONSE']._serialized_end=440
  _globals['_REPOSITORYSERVICE']._serialized_start=443
  _globals['_REPOSITORYSERVICE']._serialized_end=912
# @@protoc_insertion_point(module_scope)
