name: Packaging

on:
  push:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/tests.yaml

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
      
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Package Server Deb
        run: |
          cd server
          make build
          make package_deb
        
      - name: Package Client Deb
        run: |
          cd client
          make build
          make package_deb

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: "0.6.7"

      - name: Install the project
        run: uv sync --all-extras --dev
      
      - name: Install flatpak
        run: |
          sudo apt-get install flatpak flatpak-builder

      - name: Build
        run: |
          source .venv/bin/activate
          cd interface
          make build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
