name: Packaging

on:
  push:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/tests.yaml

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
      
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Package Server Deb
        run: |
          cd server
          make build
          make package_deb
        
      - name: Package Client Deb
        run: |
          cd client
          make build
          make package_deb

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
