name: Packaging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v3

      - name: Build Deb and Snap
        run: make build_and_package
